### PR TITLE
1.21.2

### PR DESCRIPTION
**Pull request by arnokeesman**
### persistent state
So they removed saving from persistent state, they only create the compound now, saving is left up to the implementation I guess, there isn't even an abstract method for it
How do you think error handling should be taken care of there?

### loom
Updating seems to include a part that was compiled using loom 1.8
it's also the new recommended
it requires gradle 8.10, so uhhm that's taken care of as well
it's in its own commit, won't hurt to cherry pick to all "active" versions

### CODE REVIEW

**Comment by John-Paul-R** [comment]
The just-let-me-save-my-file saga continues lol

I'll take a look at the old error handling in just a bit. My instinct is mostly to mirror what the old base method did internally for now.

**Comment by arnokeesman** [comment]
with how much they moved to the toNbt method, this should be identical
release also dropped, so updated a couple numbers again

**Comment by John-Paul-R** [comment]
Only difference seems to be that they were simply logging the exception, instead of rethrowing. E: oh, which I see is reflected here, now

**Comment by arnokeesman** [comment]
bit weird, as they do mark it as not dirty
so uhhh, bye data
but oh well, it should just work anyway

**Comment by John-Paul-R** [comment]
Handling that seems to be the job of PersistentStateManager for MC types now. Not sure if/how they handle the exception inside there. (Started looking at switching kits to use it yesterday, bc it implicitly gives you versioning and async saves, but, it isn't entirely straightforward, and I don't remember the details.)

**Pull request merged**
